// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPizzaApp.Data;

namespace WebPizzaApp.Migrations
{
    [DbContext(typeof(WebPizzaAppDbContext))]
    [Migration("20200804121221_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPizzaApp.Data.Allapot", b =>
                {
                    b.Property<int>("AllapotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Megnevezes")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AllapotId");

                    b.ToTable("Allapotok");

                    b.HasData(
                        new
                        {
                            AllapotId = 1,
                            Megnevezes = "Készítés alatt"
                        },
                        new
                        {
                            AllapotId = 2,
                            Megnevezes = "Kiszállítás alatt"
                        },
                        new
                        {
                            AllapotId = 3,
                            Megnevezes = "Kiszállítva"
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.Cim", b =>
                {
                    b.Property<int>("CimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Csengo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Hazszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Irsz")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(4);

                    b.Property<int?>("MegrendeloId")
                        .HasColumnType("int");

                    b.Property<string>("Utca")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Varos")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("CimId");

                    b.HasIndex("MegrendeloId");

                    b.ToTable("Cimek");

                    b.HasData(
                        new
                        {
                            CimId = 1,
                            Csengo = "20",
                            Hazszam = "110",
                            Irsz = "1111",
                            MegrendeloId = 1,
                            Utca = "Fehérvári út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 2,
                            Csengo = "20",
                            Hazszam = "110",
                            Irsz = "1111",
                            MegrendeloId = 2,
                            Utca = "Fehérvári út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 3,
                            Csengo = "3",
                            Hazszam = "23",
                            Irsz = "2222",
                            MegrendeloId = 3,
                            Utca = "Dózsa György út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 4,
                            Csengo = "5",
                            Hazszam = "45",
                            Irsz = "3333",
                            MegrendeloId = 3,
                            Utca = "István út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 5,
                            Csengo = "11",
                            Hazszam = "70",
                            Irsz = "4444",
                            MegrendeloId = 4,
                            Utca = "Attila út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 6,
                            Csengo = "10",
                            Hazszam = "12",
                            Irsz = "5555",
                            MegrendeloId = 5,
                            Utca = "Erzsébet út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 7,
                            Csengo = "7",
                            Hazszam = "24",
                            Irsz = "6666",
                            MegrendeloId = 5,
                            Utca = "Mária út.",
                            Varos = "Budapest"
                        },
                        new
                        {
                            CimId = 8,
                            Csengo = "2",
                            Hazszam = "2",
                            Irsz = "7777",
                            MegrendeloId = 5,
                            Utca = "László út.",
                            Varos = "Budapest"
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.Futar", b =>
                {
                    b.Property<int>("FutarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("FutarId");

                    b.ToTable("Futarok");

                    b.HasData(
                        new
                        {
                            FutarId = 1,
                            Nev = "Villám Vili"
                        },
                        new
                        {
                            FutarId = 2,
                            Nev = "Lajhár Laci"
                        },
                        new
                        {
                            FutarId = 3,
                            Nev = "Gyors Gyuri"
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.Megrendelo", b =>
                {
                    b.Property<int>("MegrendeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MegrendeloId");

                    b.ToTable("Megrendelok");

                    b.HasData(
                        new
                        {
                            MegrendeloId = 1,
                            Nev = "Éhes Elemér"
                        },
                        new
                        {
                            MegrendeloId = 2,
                            Nev = "Éhes Eszter"
                        },
                        new
                        {
                            MegrendeloId = 3,
                            Nev = "Hasas Hedvig"
                        },
                        new
                        {
                            MegrendeloId = 4,
                            Nev = "Vega Viktor"
                        },
                        new
                        {
                            MegrendeloId = 5,
                            Nev = "Vékony Vilma"
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("PizzaId");

                    b.ToTable("Pizzak");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            Nev = "Magyaros"
                        },
                        new
                        {
                            PizzaId = 2,
                            Nev = "Húsos"
                        },
                        new
                        {
                            PizzaId = 3,
                            Nev = "Szalámis"
                        },
                        new
                        {
                            PizzaId = 4,
                            Nev = "Sajtos"
                        },
                        new
                        {
                            PizzaId = 5,
                            Nev = "Mexikói"
                        },
                        new
                        {
                            PizzaId = 6,
                            Nev = "Spenótos"
                        },
                        new
                        {
                            PizzaId = 7,
                            Nev = "Sonkás"
                        },
                        new
                        {
                            PizzaId = 8,
                            Nev = "Gombás"
                        },
                        new
                        {
                            PizzaId = 9,
                            Nev = "Vega"
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.PizzaRendeles", b =>
                {
                    b.Property<int>("PizzaRendelesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("RendelesId")
                        .HasColumnType("int");

                    b.HasKey("PizzaRendelesId");

                    b.HasIndex("PizzaId");

                    b.HasIndex("RendelesId");

                    b.ToTable("PizzaRendelesek");

                    b.HasData(
                        new
                        {
                            PizzaRendelesId = 1,
                            PizzaId = 1,
                            RendelesId = 1
                        },
                        new
                        {
                            PizzaRendelesId = 2,
                            PizzaId = 4,
                            RendelesId = 2
                        },
                        new
                        {
                            PizzaRendelesId = 3,
                            PizzaId = 9,
                            RendelesId = 3
                        },
                        new
                        {
                            PizzaRendelesId = 4,
                            PizzaId = 2,
                            RendelesId = 3
                        },
                        new
                        {
                            PizzaRendelesId = 5,
                            PizzaId = 5,
                            RendelesId = 4
                        },
                        new
                        {
                            PizzaRendelesId = 6,
                            PizzaId = 3,
                            RendelesId = 5
                        },
                        new
                        {
                            PizzaRendelesId = 7,
                            PizzaId = 3,
                            RendelesId = 5
                        },
                        new
                        {
                            PizzaRendelesId = 8,
                            PizzaId = 9,
                            RendelesId = 5
                        },
                        new
                        {
                            PizzaRendelesId = 9,
                            PizzaId = 5,
                            RendelesId = 5
                        },
                        new
                        {
                            PizzaRendelesId = 10,
                            PizzaId = 2,
                            RendelesId = 6
                        },
                        new
                        {
                            PizzaRendelesId = 11,
                            PizzaId = 1,
                            RendelesId = 7
                        },
                        new
                        {
                            PizzaRendelesId = 12,
                            PizzaId = 1,
                            RendelesId = 8
                        },
                        new
                        {
                            PizzaRendelesId = 13,
                            PizzaId = 4,
                            RendelesId = 8
                        },
                        new
                        {
                            PizzaRendelesId = 14,
                            PizzaId = 7,
                            RendelesId = 9
                        },
                        new
                        {
                            PizzaRendelesId = 15,
                            PizzaId = 8,
                            RendelesId = 9
                        },
                        new
                        {
                            PizzaRendelesId = 16,
                            PizzaId = 6,
                            RendelesId = 9
                        },
                        new
                        {
                            PizzaRendelesId = 17,
                            PizzaId = 2,
                            RendelesId = 10
                        },
                        new
                        {
                            PizzaRendelesId = 18,
                            PizzaId = 2,
                            RendelesId = 11
                        },
                        new
                        {
                            PizzaRendelesId = 19,
                            PizzaId = 1,
                            RendelesId = 12
                        },
                        new
                        {
                            PizzaRendelesId = 20,
                            PizzaId = 5,
                            RendelesId = 12
                        },
                        new
                        {
                            PizzaRendelesId = 21,
                            PizzaId = 7,
                            RendelesId = 12
                        },
                        new
                        {
                            PizzaRendelesId = 22,
                            PizzaId = 3,
                            RendelesId = 13
                        },
                        new
                        {
                            PizzaRendelesId = 23,
                            PizzaId = 4,
                            RendelesId = 13
                        },
                        new
                        {
                            PizzaRendelesId = 24,
                            PizzaId = 2,
                            RendelesId = 13
                        },
                        new
                        {
                            PizzaRendelesId = 25,
                            PizzaId = 2,
                            RendelesId = 13
                        },
                        new
                        {
                            PizzaRendelesId = 26,
                            PizzaId = 9,
                            RendelesId = 14
                        },
                        new
                        {
                            PizzaRendelesId = 27,
                            PizzaId = 3,
                            RendelesId = 14
                        },
                        new
                        {
                            PizzaRendelesId = 28,
                            PizzaId = 8,
                            RendelesId = 15
                        },
                        new
                        {
                            PizzaRendelesId = 29,
                            PizzaId = 1,
                            RendelesId = 16
                        },
                        new
                        {
                            PizzaRendelesId = 30,
                            PizzaId = 4,
                            RendelesId = 17
                        },
                        new
                        {
                            PizzaRendelesId = 31,
                            PizzaId = 2,
                            RendelesId = 17
                        },
                        new
                        {
                            PizzaRendelesId = 32,
                            PizzaId = 6,
                            RendelesId = 17
                        },
                        new
                        {
                            PizzaRendelesId = 33,
                            PizzaId = 3,
                            RendelesId = 18
                        },
                        new
                        {
                            PizzaRendelesId = 34,
                            PizzaId = 7,
                            RendelesId = 18
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.Rendeles", b =>
                {
                    b.Property<int>("RendelesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllapotId")
                        .HasColumnType("int");

                    b.Property<int?>("CimId")
                        .HasColumnType("int");

                    b.Property<int?>("FutarId")
                        .HasColumnType("int");

                    b.HasKey("RendelesId");

                    b.HasIndex("AllapotId");

                    b.HasIndex("CimId");

                    b.HasIndex("FutarId");

                    b.ToTable("Rendelesek");

                    b.HasData(
                        new
                        {
                            RendelesId = 1,
                            AllapotId = 3,
                            CimId = 3,
                            FutarId = 1
                        },
                        new
                        {
                            RendelesId = 2,
                            AllapotId = 3,
                            CimId = 2,
                            FutarId = 1
                        },
                        new
                        {
                            RendelesId = 3,
                            AllapotId = 3,
                            CimId = 5,
                            FutarId = 2
                        },
                        new
                        {
                            RendelesId = 4,
                            AllapotId = 3,
                            CimId = 2,
                            FutarId = 3
                        },
                        new
                        {
                            RendelesId = 5,
                            AllapotId = 3,
                            CimId = 2,
                            FutarId = 3
                        },
                        new
                        {
                            RendelesId = 6,
                            AllapotId = 3,
                            CimId = 6,
                            FutarId = 3
                        },
                        new
                        {
                            RendelesId = 7,
                            AllapotId = 2,
                            CimId = 8,
                            FutarId = 2
                        },
                        new
                        {
                            RendelesId = 8,
                            AllapotId = 2,
                            CimId = 3,
                            FutarId = 1
                        },
                        new
                        {
                            RendelesId = 9,
                            AllapotId = 3,
                            CimId = 2,
                            FutarId = 1
                        },
                        new
                        {
                            RendelesId = 10,
                            AllapotId = 2,
                            CimId = 5,
                            FutarId = 2
                        },
                        new
                        {
                            RendelesId = 11,
                            AllapotId = 2,
                            CimId = 4,
                            FutarId = 2
                        },
                        new
                        {
                            RendelesId = 12,
                            AllapotId = 2,
                            CimId = 2,
                            FutarId = 1
                        },
                        new
                        {
                            RendelesId = 13,
                            AllapotId = 2,
                            CimId = 4,
                            FutarId = 1
                        },
                        new
                        {
                            RendelesId = 14,
                            AllapotId = 2,
                            CimId = 1,
                            FutarId = 3
                        },
                        new
                        {
                            RendelesId = 15,
                            AllapotId = 2,
                            CimId = 3,
                            FutarId = 2
                        },
                        new
                        {
                            RendelesId = 16,
                            AllapotId = 1,
                            CimId = 7
                        },
                        new
                        {
                            RendelesId = 17,
                            AllapotId = 1,
                            CimId = 7
                        },
                        new
                        {
                            RendelesId = 18,
                            AllapotId = 1,
                            CimId = 5
                        });
                });

            modelBuilder.Entity("WebPizzaApp.Data.Cim", b =>
                {
                    b.HasOne("WebPizzaApp.Data.Megrendelo", "Megrendelo")
                        .WithMany("Cimek")
                        .HasForeignKey("MegrendeloId");
                });

            modelBuilder.Entity("WebPizzaApp.Data.PizzaRendeles", b =>
                {
                    b.HasOne("WebPizzaApp.Data.Pizza", "Pizza")
                        .WithMany("PizzaRendelesek")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPizzaApp.Data.Rendeles", "Rendeles")
                        .WithMany("PizzaRendelesek")
                        .HasForeignKey("RendelesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPizzaApp.Data.Rendeles", b =>
                {
                    b.HasOne("WebPizzaApp.Data.Allapot", "Allapot")
                        .WithMany("Rendelesek")
                        .HasForeignKey("AllapotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPizzaApp.Data.Cim", "Cim")
                        .WithMany()
                        .HasForeignKey("CimId");

                    b.HasOne("WebPizzaApp.Data.Futar", "Futar")
                        .WithMany("Rendelesek")
                        .HasForeignKey("FutarId");
                });
#pragma warning restore 612, 618
        }
    }
}
